airbytehq/airbyte-protocol

.github/workflows/publish-to-pypi-manually.yml, protocol-models/bin/generate-python-classes-docker.sh, protocol-models/python/setup.py
Supports Py3.8 and stops publishing to test Pypi because test pypi is no longer part of our workflow
I have manually verified there is no diff between models generated with Python 3.8 and those generated with Python 3.9
=> Support python 3.8 and stop publishing to test PyPi

.github/actions/publish/action.yml
Seems like the expected env var for npm auth is NPM_TOKEN
=> ci: NPM_TOKEN for npm auth

readme.md
The previous read me was not clear how to release a new Airbyte protocol.
This current readme provides a very clear list of what to do.
It also corrects some typos.
=> docs: better publishing instructions.

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml
Fixes indentation that prevented the `AirbyteStreamStatusTraceMessage` from being generated properly.
=> fix: Fix indentation

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml
Removes the `success` optional field from the `AirbyteStreamStatusTraceMessage` in favor of explicit values in the `AirbyteStreamStatus` enumeration.
=> fix: Remove success in favor of explicit status enum values

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml
Relates to https://github.com/airbytehq/airbyte/issues/15019
[Protocol Change Proposal doc](https://docs.google.com/document/d/1vBAHI9r5qcD8WJc0GXaWEsRrmrvKd4NNvmreUDrqzcA/edit?usp=sharing)
Removes authSpecification from the Airbyte protocol, as it has been replaced by advancedAuth. 
This should only be merged once all connectors in the Airbyte catalog have been migrated to advancedAuth and all references to `authSpecification` have been removed from the Airbyte platform. See the [epic](https://app.zenhub.com/workspaces/connector-extensibility-6257455decf3920012f4e872/issues/gh/airbytehq/airbyte/15019) for the status of the connector migrations.
EDIT: All connectors have now been migrated off of authSpecification, and all references have been removed from the Airbyte platform, so this …
=> refactor: Remove authSpecification from Airbyte protocol

protocol-models/python/setup.py
The pydantic version requirement is fairly strict and aligned with the CDK version requirement. As https://github.com/airbytehq/airbyte/pull/28854 will relax the version requirement to everything (equal-)greater than 1.9.2 but lower than 2, this PR aligns the version requirements
=> fix: Python package - relax pydantic depenency version requirement

protocol-models/src/main/java/io/airbyte/protocol/models/JsonSchemas.java, protocol-models/src/test/java/io/airbyte/protocol/models/CatalogHelpersTest.java, protocol-models/src/test/resources/valid_schema.json, protocol-models/src/test/resources/valid_schema2.json
Related to https://github.com/airbytehq/oncall/issues/2703
The goal is to relax the hard requirement of the json node being an object.
The release of a new stripe catalog revealed that
1. We had been successfully using a catalog for 2 months with a node considered invalid by this diff tool
2. That this diff tool would fail when prevented with a valid json object, that we just didnt like
Because of this we opted to change the behaviour of this diff to simply skip the node.
This then causes the diff to treat the field as a new field when it becomes valid
We could have edited all catalogs and configured catalogs in the last two months for stripe but that was deemed to risky and didnt solve the root issue
We could make this so the diff treats the change from invalid type to valid as an …
=> fix: Skip dont error when invalid jsonSchemaNode is found during traversal

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml
Adds analytics trace message according to https://docs.google.com/document/d/1ZYoCs79GAfTn-x0RL76r4gWm1IWXqJ0cMP5K1RUPeWM/edit
This is not a publicly documented message type and mostly intended for internal use. Because of this, it's marked as a refactoring similar to https://github.com/airbytehq/airbyte-protocol/pull/39
=> refactor: Add analytics trace message type

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml
Follow-up to https://github.com/airbytehq/airbyte-protocol/pull/45 to add more details to the descriptions.
=> fix: Add more documentation to analytics message

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml
Described in detail [here](https://docs.google.com/document/d/1bO__n57LVRMba1TDoZrdaDNbUrgqKnyicaT8DiQxiGI/edit)
`AirbyteStateStats` augments `AirbyteStateMessage` with optional information to track the number of records observed for each state chunk by the source and destination.  A mismatch in these counts indicates that records were lost during the sync
=> feat: add `AirbyteStateStats`

.github/workflows/pull-request-publish.yml
Pypi now requires that we use 2fa. This forces us to use API keys and as a result we can no longer reuse the same password between test and prod (probably a good thing!)
=> Pypi: Update to use new test creds

protocol-models/src/main/java/io/airbyte/protocol/models/CatalogHelpers.java, protocol-models/src/test/java/io/airbyte/protocol/models/CatalogHelpersTest.java
Function `getCatalogDiff` compares the existing source catalog with the newly discovered one and if there's a difference, it includes the corresponding stream in the update that shows up in the UI. However, a given stream may not be toggled (selected) by the customer,  thus it should not be included in the update. This change ensures that, in addition to doing a comparison between the new and old catalog, the configured catalog must also be present. Inactive streams will not show up in the ConfiguredCatalog.
Solves https://github.com/airbytehq/airbyte/issues/23361
=> fix: only add user selected streams to the catalog diff

protocol-models/src/main/resources/airbyte_protocol/v1/airbyte_protocol.yaml
We do not use V1. Instead of duplicate, potential drift and confusion, let's remove V1 for now and re-introduce when we are ready to move to V1.
=> fix: Removed unused V1.

protocol-models/python/setup.py
Currently, the python distribution of the protocol models doesn't have a [`py.typed` file](https://peps.python.org/pep-0561/) which throws off mypy. This PR fixes this issue
=> fix: Add py.typed to python distribution

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml, protocol-models/src/test/java/io/airbyte/protocol/models/CatalogHelpersTest.java
[Related Doc](https://docs.google.com/document/d/1eujDX1katRSwfWEploscqPthoO6etV5_q-Xy7wVn4vw/edit) and [Protocol Change Doc](https://docs.google.com/document/d/1yLUWO569E7WJJtC-v284fEq4AXNQoKJ5o4bLHxf2acI/edit)
In order to help track the lineage of record changes along throughout a sync, a new _optional_ property is added to `AirbyteRecordMessage` that will store per-record errors that will eventually be stored in the destination.  
As a reminder of our starting assumptions:
* "data errors" are not "sync errors", and therefore should not block/fail a sync.
* Some data is just too big to process or store.
* Any part of the Airbyte platform might need to modify a record field for size reasons.  
For example, consider the following totally realistic example record:
```js
{
type: "RECORD", …
```
=> feat: `AirbyteRecordMessageMeta` for per-record lineage and changes

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml
Explain why recordCount is a number instead of an integer
=> docs: Explain why recordCount is a number instead of an integer

.env, protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml
This is the implementation of https://docs.google.com/document/d/1MAReO2FwV7l-ETAZTLScrcX4DZgEP7N_aCtOC9keAiU/edit
=> feat: Proposal for refreshes needed metadata

build.gradle, protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml
After [updating our java and gradle versions](https://github.com/airbytehq/airbyte-protocol/pull/97), code compiles, but does not build due to various things we run during the build like `spotBugs` and `spotless` erroring out. This updates the dependencies to java 21 - compatible versions.
=> fix: fix build issues with plugin versions not compatible with java 21

.github/workflows/pull-request-publish.yml
some changes outside of the `"protocol-models/**"` paths affect our ability to build + run code. Run this step on all PRs so that we can block merging if the java build or the generation into other languages fails.
=> ci: always run build + publish artifacts on pull requests

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml
While working on the migration for `TikTok Marketing` OAuthFlow, there was a need to encode the `access_token_url` query parameters to `json string` instead of `url_encoded` parameters. 
The `access_token_params` is there to provide such a functionality, in order to match the actual spec provided with the designed `protocol` DeclarativeOAuth spec this property should exist at the `protocol` level.
- add the `access_token_params` object property to the `OAuthConfigSpecification.oauth_connector_input_specification.properties`
- made the `additionalProperties` set to `true` to allow future lazy spec improvements, even though the protocol could be behind of the actual source / destination spec, allowing us to provide more properties to work with.
=> fix: (DeclarativeOAuthFlow) - add `access_token_params` property to match the actual spec properties

protocol-models/bin/generate-python-dataclasses.sh, protocol-models/bin/generate-python-pydantic-v2.sh
Some dependency changed in the background on our build pipeline causing our `jsonschema` files to be interpretted as `json` and breaking our release ci for both main and individual branches.
Discovered in #106 
Explicitly mark inout files as jsonschema
=> ci: fix pydantic v2 model gen by explicitly mark input files as jsonschema

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml
Resolving:
- https://github.com/airbytehq/airbyte-internal-issues/issues/11422
After this change: https://github.com/airbytehq/airbyte-platform-internal/pull/15040, there is no need to have the `extract_output` as the `required` field to be provided, we will leverage the `complete_oauth_output_specification.path_in_oauth_response` instead.
No impact is expected. This is not a breaking change.
=> fix: (DeclarativeOAuthFlow) - make the `extract_output` Optional; correct the descriptions

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml
Today we define and publish V1 along side V0. This is a remnant from the V1 breaking change a few years back that we are no longer doing.
Unfortunately this means we now have **different components using both V1 and V0 code packages**. It's also easy for us to accidentally update one file and not the other - **drift exists today**. All of this is confusing.
I want to remove V1 from the protocol repo and move everyone over to V0. We'll reintroduce V1 when we are properly migrating. Step 1 is equalising both files.
=> chore: equalise V0 and V1 protocol definitions.

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml
Reverts airbytehq/airbyte-protocol#115
PR title should have fix to trigger the right publishing flow.
=> chore: revert "chore: equalise V0 and V1 protocol definitions."

.github/workflows/manual-publish.yml, .github/workflows/master-release.yml
Looks like the Python publishing creds are incorrect:
* master fails [here](https://github.com/airbytehq/airbyte-protocol/actions/runs/14138575451/job/39615810115#step:4:891).
* manual test with same creds off main fails [here](https://github.com/airbytehq/airbyte-protocol/actions/runs/14210518255/job/39816728688#step:3:890).
I've regenerated them and confirmed they work via a successful manual publish off this branch: https://github.com/airbytehq/airbyte-protocol/actions/runs/14210797370/job/39817514819
This PR updates these to the correct secrets. I'll remove the old secrets after this.
=> chore: fix Python Publishing Creds.

protocol-models/src/main/java/io/airbyte/protocol/models/AirbyteProtocolSchema.java, protocol-models/src/main/java/io/airbyte/protocol/models/AirbyteStreamNameNamespacePair.java, protocol-models/src/main/java/io/airbyte/protocol/models/CatalogHelpers.java, protocol-models/src/main/java/io/airbyte/protocol/models/CommonField.java, protocol-models/src/main/java/io/airbyte/protocol/models/Field.java, protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/test/java/io/airbyte/protocol/models/AirbyteProtocolSchemaTest.java, protocol-models/src/test/java/io/airbyte/protocol/models/CatalogHelpersTest.java
Turns out this affects the Python CDK. See https://github.com/airbytehq/airbyte-protocol/issues/124.
Revert to unblock OSS users.
=> fix: "fix: remove V1 models"

.env, protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml
Adds support for "file based" streams — streams consisting of files _and_ their associated metadata. 
These streams may be synced alongside normal streams, enabling a single connection to support both files and records.
Detailed information explaining the motivations of the supported feature and the changes themselves can be found in the proposal doc linked below.
[Protocol Proposal Doc](https://docs.google.com/document/d/1SaGZEMXTku6IC3MWWTvzK_bWtJr1vcP7I3mRHPVH-Tc/edit?tab=t.0)
[Feature description](https://docs.google.com/document/d/1CFPWkHD2cfJ9cHpqI-T3G6z7qjWFWUepA0d6cl9LZkY/edit?tab=t.0#heading=h.ka3phxnzyvn4)
Evolution of [spike draft](https://github.com/airbytehq/airbyte-protocol/pull/111)
=> feat: add support for file+metadata streams

protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml, protocol-models/src/main/resources/airbyte_protocol/v0/airbyte_protocol.yaml
I was trying to update destination-salesforce and destination-customer-io with the latest changes and the fact that the field for the json schema is called `schema` clashes with pydantic reserved word `schema` which has the side effect of having the field named as `schema_` instead of `schema`. This problem occurs in two places:
* The python code where we need to write `schema_` instead of just `schema`. I’m not too attached to fixing this right now because we were looking into having the destinations in Kotlin but it is bad DX
* The serialization of the Airbyte message for the discovered catalog generates objects with field `schema_` instead of `schema` and this one is an issue as it does not allow us to return the right object
There are a couple of paths forward I see:
1. Fix the …
=> feat: rename schema to json-schema
